### ISSUE TITLE
Support for NodeJS v6.9.1?

### ISSUE THREAD

**Issue by dkilcy** [scality/vaultclient#125]
GA6.3.2

When running vaultclient with NodeJS 6.9.1 on CentOS 7 I get a "SignatureDoesNotMatch" when attempting to perform a command using the vaultclient.    I installed Node v4.5.0 to match what the container is running, and it works.

Is this a known issue or should I gather logs to help diagnose the problem?

6.X is the current supported release and available from the EPEL.

**Comment by alexandre-merle** [comment]
yes it's a known issue, we do not support the new node LTS
