### ISSUE TITLE
Loss of transparency with S3 API

### ISSUE THREAD

**Issue by LaureVergeron** [scality/vaultclient#36]
I didn't notice on the PR, but the way the arguments are passed to the functions is not exactly the same as what AWS CLI expects. For example, for ```create-user```
AWS CLI: ```create-user --account-name <> --user-name <> --user-password <> --user-email <>```
Scality CLI: ```create-user --account-name <> --name <> --password <> --email <>```
We probably want to fix that some time

**Comment by alexandre-merle** [comment]
Since amazon iam routes are longer in vaultclient, closing this issue :)
